# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fb09e66b90e71f2944c9aa1f213530ec"
name = "assessment-app"
handle = "assessment-app"
application_url = "https://allow-wrapped-said-ppc.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "vowelweb-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://allow-wrapped-said-ppc.trycloudflare.com/auth/callback",
  "https://allow-wrapped-said-ppc.trycloudflare.com/auth/shopify/callback",
  "https://allow-wrapped-said-ppc.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
